// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAccount");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("email");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    b.Property<int>("IdStateAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("idStateAccount");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("password");

                    b.HasKey("IdAccount")
                        .HasName("PK__Account__DA18132C73016F04");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdStateAccount");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Persistence.AssignQueue", b =>
                {
                    b.Property<int>("IdAssignQueue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAssignQueue");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAssignQueue"));

                    b.Property<int>("IdQueueVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idQueueVehicle");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.HasKey("IdAssignQueue")
                        .HasName("PK__AssignQu__239C1934B49D7544");

                    b.HasIndex("IdQueueVehicle");

                    b.HasIndex("IdVehicle");

                    b.ToTable("AssignQueue", (string)null);
                });

            modelBuilder.Entity("Persistence.Assignment", b =>
                {
                    b.Property<int>("IdAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAssignment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAssignment"));

                    b.Property<DateTime?>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("assignmentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("idAccount");

                    b.Property<int>("IdHeadquarter")
                        .HasColumnType("int")
                        .HasColumnName("idHeadquarter");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.HasKey("IdAssignment")
                        .HasName("PK__Assignme__89A425AA365E3276");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdHeadquarter");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("Persistence.Billing", b =>
                {
                    b.Property<int>("IdBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBilling");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBilling"));

                    b.Property<DateTime?>("BillingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("billingDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documentNumber");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int")
                        .HasColumnName("idCompany");

                    b.Property<int>("IdPaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("idPaymentMethod");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    b.Property<string>("OperationPayCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operationPayCode");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("totalAmount");

                    b.HasKey("IdBilling")
                        .HasName("PK__Billing__83EAF8A22AEAA961");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdPaymentMethod");

                    b.HasIndex("IdPerson");

                    b.ToTable("Billing", (string)null);
                });

            modelBuilder.Entity("Persistence.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCompany");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"));

                    b.Property<string>("BusinessName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("businessName");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("FiscalAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fiscalAddress");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ruc");

                    b.HasKey("IdCompany")
                        .HasName("PK__Company__BBAEF00313940EAF");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Persistence.DepartureTime", b =>
                {
                    b.Property<int>("IdDepartureTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDepartureTime");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartureTime"));

                    b.Property<TimeOnly>("Hour")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("hour");

                    b.Property<int>("IdTravelRoute")
                        .HasColumnType("int")
                        .HasColumnName("idTravelRoute");

                    b.HasKey("IdDepartureTime")
                        .HasName("PK__Departur__45B7BAA8B434CCC9");

                    b.HasIndex("IdTravelRoute");

                    b.ToTable("DepartureTime", (string)null);
                });

            modelBuilder.Entity("Persistence.DetailVehicle", b =>
                {
                    b.Property<int>("IdDetailVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDetailVehicle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetailVehicle"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("color");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seatNumber");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("vehicleType");

                    b.HasKey("IdDetailVehicle")
                        .HasName("PK__DetailVe__CD0976F5647EA070");

                    b.HasIndex("IdVehicle");

                    b.ToTable("DetailVehicle", (string)null);
                });

            modelBuilder.Entity("Persistence.DocumentVehicle", b =>
                {
                    b.Property<int>("IdDocumentVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDocumentVehicle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentVehicle"));

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expirationDate");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.HasKey("IdDocumentVehicle")
                        .HasName("PK__Document__61EE4615336FC427");

                    b.HasIndex("IdVehicle");

                    b.ToTable("DocumentVehicle", (string)null);
                });

            modelBuilder.Entity("Persistence.Headquarter", b =>
                {
                    b.Property<int>("IdHeadquarter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHeadquarter");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHeadquarter"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int")
                        .HasColumnName("idCompany");

                    b.Property<int>("IdStateHeadquarter")
                        .HasColumnType("int")
                        .HasColumnName("idStateHeadquarter");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("isMain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("province");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registrationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdHeadquarter")
                        .HasName("PK__Headquar__D1396C9F6A474DFA");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdStateHeadquarter");

                    b.ToTable("Headquarter", (string)null);
                });

            modelBuilder.Entity("Persistence.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNotification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<int>("IdNotificationState")
                        .HasColumnType("int")
                        .HasColumnName("idNotificationState");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<string>("Message")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("message");

                    b.HasKey("IdNotification")
                        .HasName("PK__Notifica__22C02321774CD52A");

                    b.HasIndex("IdNotificationState");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdTrip");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Persistence.NotificationState", b =>
                {
                    b.Property<int>("IdNotificationState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNotificationState");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificationState"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdNotificationState")
                        .HasName("PK__Notifica__56E98973A736C9D1");

                    b.ToTable("NotificationState", (string)null);
                });

            modelBuilder.Entity("Persistence.PaymentMethod", b =>
                {
                    b.Property<int>("IdPaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPaymentMethod");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaymentMethod"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("IdPaymentMethod")
                        .HasName("PK__PaymentM__4568774731A28353");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("Persistence.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<int>("IdTypeDocument")
                        .HasColumnType("int")
                        .HasColumnName("idTypeDocument");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("NumberIdentityDocument")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numberIdentityDocument");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("IdPerson")
                        .HasName("PK__Person__BAB33700FB6BEB16");

                    b.HasIndex("IdTypeDocument");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Persistence.Place", b =>
                {
                    b.Property<int>("IdPlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPlace");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlace"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("IdPlace")
                        .HasName("PK__Place__39B84B90DB4830AB");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("Persistence.QueueVehicle", b =>
                {
                    b.Property<int>("IdQueueVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idQueueVehicle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQueueVehicle"));

                    b.Property<int?>("IdDepartureTime")
                        .HasColumnType("int")
                        .HasColumnName("idDepartureTime");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.HasKey("IdQueueVehicle")
                        .HasName("PK__QueueVeh__07518E363F347379");

                    b.HasIndex("IdDepartureTime");

                    b.ToTable("QueueVehicle", (string)null);
                });

            modelBuilder.Entity("Persistence.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.HasKey("IdRole")
                        .HasName("PK__Role__E5045C54566FFF61");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Persistence.RouteAssignment", b =>
                {
                    b.Property<int>("IdRouteAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRouteAssignment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRouteAssignment"));

                    b.Property<DateOnly?>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("assignmentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    b.Property<int>("IdTravelRoute")
                        .HasColumnType("int")
                        .HasColumnName("idTravelRoute");

                    b.HasKey("IdRouteAssignment")
                        .HasName("PK__RouteAss__1B777D2D55E29F8A");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdTravelRoute");

                    b.ToTable("RouteAssignment", (string)null);
                });

            modelBuilder.Entity("Persistence.Seat", b =>
                {
                    b.Property<int>("IdSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSeat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeat"));

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.HasKey("IdSeat")
                        .HasName("PK__Seat__C5963E9B8065B8D3");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("Persistence.SeatVehicle", b =>
                {
                    b.Property<int>("IdSeatVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSeatVehicle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeatVehicle"));

                    b.Property<int>("IdSeat")
                        .HasColumnType("int")
                        .HasColumnName("idSeat");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.Property<bool?>("StateSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("stateSeat");

                    b.HasKey("IdSeatVehicle")
                        .HasName("PK__SeatVehi__D7A52E7BBEFBD957");

                    b.HasIndex("IdSeat");

                    b.HasIndex("IdVehicle");

                    b.ToTable("SeatVehicle", (string)null);
                });

            modelBuilder.Entity("Persistence.StateAccount", b =>
                {
                    b.Property<int>("IdStateAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idStateAccount");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStateAccount"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("IdStateAccount")
                        .HasName("PK__StateAcc__D19B468F2C2B2DEB");

                    b.ToTable("StateAccount", (string)null);
                });

            modelBuilder.Entity("Persistence.StateHeadquarter", b =>
                {
                    b.Property<int>("IdStateHeadquarter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idStateHeadquarter");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStateHeadquarter"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdStateHeadquarter")
                        .HasName("PK__StateHea__33807AF2CEDFF001");

                    b.ToTable("StateHeadquarter", (string)null);
                });

            modelBuilder.Entity("Persistence.StateTrip", b =>
                {
                    b.Property<int>("IdStateTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idStateTrip");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStateTrip"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdStateTrip")
                        .HasName("PK__StateTri__355FCB80AEC7F082");

                    b.ToTable("StateTrip", (string)null);
                });

            modelBuilder.Entity("Persistence.TicketState", b =>
                {
                    b.Property<int>("IdTicketState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTicketState");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketState"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdTicketState")
                        .HasName("PK__TicketSt__FC6BA6B36D565568");

                    b.ToTable("TicketState", (string)null);
                });

            modelBuilder.Entity("Persistence.TravelRoute", b =>
                {
                    b.Property<int>("IdTravelRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTravelRoute");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTravelRoute"));

                    b.Property<int>("IdPlaceA")
                        .HasColumnType("int")
                        .HasColumnName("idPlaceA");

                    b.Property<int>("IdPlaceB")
                        .HasColumnType("int")
                        .HasColumnName("idPlaceB");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameRoute")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameRoute");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.HasKey("IdTravelRoute")
                        .HasName("PK__TravelRo__98ED03AEF1CA59F2");

                    b.HasIndex("IdPlaceA");

                    b.HasIndex("IdPlaceB");

                    b.ToTable("TravelRoute", (string)null);
                });

            modelBuilder.Entity("Persistence.TravelTicket", b =>
                {
                    b.Property<int>("IdTravelTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTravelTicket");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTravelTicket"));

                    b.Property<int>("IdBilling")
                        .HasColumnType("int")
                        .HasColumnName("idBilling");

                    b.Property<int>("IdTicketState")
                        .HasColumnType("int")
                        .HasColumnName("idTicketState");

                    b.Property<int>("IdTravelRoute")
                        .HasColumnType("int")
                        .HasColumnName("idTravelRoute");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seatNumber");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ticketCode");

                    b.Property<DateOnly?>("TravelDate")
                        .HasColumnType("date")
                        .HasColumnName("travelDate");

                    b.HasKey("IdTravelTicket")
                        .HasName("PK__TravelTi__50775021A43CEC6D");

                    b.HasIndex("IdBilling");

                    b.HasIndex("IdTicketState");

                    b.HasIndex("IdTravelRoute");

                    b.HasIndex("IdVehicle");

                    b.ToTable("TravelTicket", (string)null);
                });

            modelBuilder.Entity("Persistence.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrip"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("arrivalDate");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime")
                        .HasColumnName("departureDate");

                    b.Property<int>("IdStateTrip")
                        .HasColumnType("int")
                        .HasColumnName("idStateTrip");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    b.HasKey("IdTrip")
                        .HasName("PK__Trip__B90DB49C53E3FE99");

                    b.HasIndex("IdStateTrip");

                    b.HasIndex("IdVehicle");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("Persistence.TypeDocument", b =>
                {
                    b.Property<int>("IdTypeDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTypeDocument");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeDocument"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdTypeDocument")
                        .HasName("PK__TypeDocu__CF96EB7B2C6199CF");

                    b.ToTable("TypeDocument", (string)null);
                });

            modelBuilder.Entity("Persistence.Vehicle", b =>
                {
                    b.Property<int>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVehicle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehicle"));

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("idPerson");

                    b.Property<int>("IdVehicleState")
                        .HasColumnType("int")
                        .HasColumnName("idVehicleState");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("plateNumber");

                    b.HasKey("IdVehicle")
                        .HasName("PK__Vehicle__B5E2475484902CD3");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdVehicleState");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Persistence.VehicleState", b =>
                {
                    b.Property<int>("IdVehicleState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVehicleState");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehicleState"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdVehicleState")
                        .HasName("PK__VehicleS__000F5CB0F92D849E");

                    b.ToTable("VehicleState", (string)null);
                });

            modelBuilder.Entity("Persistence.Account", b =>
                {
                    b.HasOne("Persistence.Person", "IdPersonNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Person");

                    b.HasOne("Persistence.Role", "IdRoleNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.HasOne("Persistence.StateAccount", "IdStateAccountNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("IdStateAccount")
                        .IsRequired()
                        .HasConstraintName("FK_Account_StateAccount");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("IdStateAccountNavigation");
                });

            modelBuilder.Entity("Persistence.AssignQueue", b =>
                {
                    b.HasOne("Persistence.QueueVehicle", "IdQueueVehicleNavigation")
                        .WithMany("AssignQueues")
                        .HasForeignKey("IdQueueVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_AssignQueue_QueueVehicle");

                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("AssignQueues")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_AssignQueue_Vehicle");

                    b.Navigation("IdQueueVehicleNavigation");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.Assignment", b =>
                {
                    b.HasOne("Persistence.Account", "IdAccountNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("IdAccount")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Account");

                    b.HasOne("Persistence.Headquarter", "IdHeadquarterNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("IdHeadquarter")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Headquarter");

                    b.Navigation("IdAccountNavigation");

                    b.Navigation("IdHeadquarterNavigation");
                });

            modelBuilder.Entity("Persistence.Billing", b =>
                {
                    b.HasOne("Persistence.Company", "IdCompanyNavigation")
                        .WithMany("Billings")
                        .HasForeignKey("IdCompany")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Company");

                    b.HasOne("Persistence.PaymentMethod", "IdPaymentMethodNavigation")
                        .WithMany("Billings")
                        .HasForeignKey("IdPaymentMethod")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_PaymentMethod");

                    b.HasOne("Persistence.Person", "IdPersonNavigation")
                        .WithMany("Billings")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Person");

                    b.Navigation("IdCompanyNavigation");

                    b.Navigation("IdPaymentMethodNavigation");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("Persistence.DepartureTime", b =>
                {
                    b.HasOne("Persistence.TravelRoute", "IdTravelRouteNavigation")
                        .WithMany("DepartureTimes")
                        .HasForeignKey("IdTravelRoute")
                        .IsRequired()
                        .HasConstraintName("FK_DepartureTime_TraveRoute");

                    b.Navigation("IdTravelRouteNavigation");
                });

            modelBuilder.Entity("Persistence.DetailVehicle", b =>
                {
                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("DetailVehicles")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_DetailVehicle_Vehicle");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.DocumentVehicle", b =>
                {
                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("DocumentVehicles")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentVehicle_Vehicle");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.Headquarter", b =>
                {
                    b.HasOne("Persistence.Company", "IdCompanyNavigation")
                        .WithMany("Headquarters")
                        .HasForeignKey("IdCompany")
                        .IsRequired()
                        .HasConstraintName("FK_Headquarter_Company");

                    b.HasOne("Persistence.StateHeadquarter", "IdStateHeadquarterNavigation")
                        .WithMany("Headquarters")
                        .HasForeignKey("IdStateHeadquarter")
                        .IsRequired()
                        .HasConstraintName("FK_Headquarter_StateHeadquarter");

                    b.Navigation("IdCompanyNavigation");

                    b.Navigation("IdStateHeadquarterNavigation");
                });

            modelBuilder.Entity("Persistence.Notification", b =>
                {
                    b.HasOne("Persistence.NotificationState", "IdNotificationStateNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdNotificationState")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_NotificationState");

                    b.HasOne("Persistence.Person", "IdPersonNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Person");

                    b.HasOne("Persistence.Trip", "IdTripNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdTrip")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Trip");

                    b.Navigation("IdNotificationStateNavigation");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("Persistence.Person", b =>
                {
                    b.HasOne("Persistence.TypeDocument", "IdTypeDocumentNavigation")
                        .WithMany("People")
                        .HasForeignKey("IdTypeDocument")
                        .IsRequired()
                        .HasConstraintName("FK_Person_IdentityDocument");

                    b.Navigation("IdTypeDocumentNavigation");
                });

            modelBuilder.Entity("Persistence.QueueVehicle", b =>
                {
                    b.HasOne("Persistence.DepartureTime", "IdDepartureTimeNavigation")
                        .WithMany("QueueVehicles")
                        .HasForeignKey("IdDepartureTime")
                        .HasConstraintName("FK_QueueVehicle_DepartureTime");

                    b.Navigation("IdDepartureTimeNavigation");
                });

            modelBuilder.Entity("Persistence.RouteAssignment", b =>
                {
                    b.HasOne("Persistence.Person", "IdPersonNavigation")
                        .WithMany("RouteAssignments")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_RouteAssignment_Person");

                    b.HasOne("Persistence.TravelRoute", "IdTravelRouteNavigation")
                        .WithMany("RouteAssignments")
                        .HasForeignKey("IdTravelRoute")
                        .IsRequired()
                        .HasConstraintName("FK_RouteAssignment_TravelRoute");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdTravelRouteNavigation");
                });

            modelBuilder.Entity("Persistence.SeatVehicle", b =>
                {
                    b.HasOne("Persistence.Seat", "IdSeatNavigation")
                        .WithMany("SeatVehicles")
                        .HasForeignKey("IdSeat")
                        .IsRequired()
                        .HasConstraintName("FK_SeatVehicle_Seat");

                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("SeatVehicles")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_SeatVehicle_Vehicle");

                    b.Navigation("IdSeatNavigation");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.TravelRoute", b =>
                {
                    b.HasOne("Persistence.Place", "IdPlaceANavigation")
                        .WithMany("TravelRouteIdPlaceANavigations")
                        .HasForeignKey("IdPlaceA")
                        .IsRequired()
                        .HasConstraintName("FK_TravelRoute_PlaceA");

                    b.HasOne("Persistence.Place", "IdPlaceBNavigation")
                        .WithMany("TravelRouteIdPlaceBNavigations")
                        .HasForeignKey("IdPlaceB")
                        .IsRequired()
                        .HasConstraintName("FK_TravelRoute_PlaceB");

                    b.Navigation("IdPlaceANavigation");

                    b.Navigation("IdPlaceBNavigation");
                });

            modelBuilder.Entity("Persistence.TravelTicket", b =>
                {
                    b.HasOne("Persistence.Billing", "IdBillingNavigation")
                        .WithMany("TravelTickets")
                        .HasForeignKey("IdBilling")
                        .IsRequired()
                        .HasConstraintName("FK_TravelTicket_Person");

                    b.HasOne("Persistence.TicketState", "IdTicketStateNavigation")
                        .WithMany("TravelTickets")
                        .HasForeignKey("IdTicketState")
                        .IsRequired()
                        .HasConstraintName("FK_TravelTicket_TicketState");

                    b.HasOne("Persistence.TravelRoute", "IdTravelRouteNavigation")
                        .WithMany("TravelTickets")
                        .HasForeignKey("IdTravelRoute")
                        .IsRequired()
                        .HasConstraintName("FK_TravelTicket_TravelRoute");

                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("TravelTickets")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_TravelTicket_Vehicle");

                    b.Navigation("IdBillingNavigation");

                    b.Navigation("IdTicketStateNavigation");

                    b.Navigation("IdTravelRouteNavigation");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.Trip", b =>
                {
                    b.HasOne("Persistence.StateTrip", "IdStateTripNavigation")
                        .WithMany("Trips")
                        .HasForeignKey("IdStateTrip")
                        .IsRequired()
                        .HasConstraintName("FK_Trip_StateTrip");

                    b.HasOne("Persistence.Vehicle", "IdVehicleNavigation")
                        .WithMany("Trips")
                        .HasForeignKey("IdVehicle")
                        .IsRequired()
                        .HasConstraintName("FK_Trip_Vehicle");

                    b.Navigation("IdStateTripNavigation");

                    b.Navigation("IdVehicleNavigation");
                });

            modelBuilder.Entity("Persistence.Vehicle", b =>
                {
                    b.HasOne("Persistence.Person", "IdPersonNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Person");

                    b.HasOne("Persistence.VehicleState", "IdVehicleStateNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("IdVehicleState")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_VehicleState");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdVehicleStateNavigation");
                });

            modelBuilder.Entity("Persistence.Account", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Persistence.Billing", b =>
                {
                    b.Navigation("TravelTickets");
                });

            modelBuilder.Entity("Persistence.Company", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("Headquarters");
                });

            modelBuilder.Entity("Persistence.DepartureTime", b =>
                {
                    b.Navigation("QueueVehicles");
                });

            modelBuilder.Entity("Persistence.Headquarter", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Persistence.NotificationState", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Persistence.PaymentMethod", b =>
                {
                    b.Navigation("Billings");
                });

            modelBuilder.Entity("Persistence.Person", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Billings");

                    b.Navigation("Notifications");

                    b.Navigation("RouteAssignments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Persistence.Place", b =>
                {
                    b.Navigation("TravelRouteIdPlaceANavigations");

                    b.Navigation("TravelRouteIdPlaceBNavigations");
                });

            modelBuilder.Entity("Persistence.QueueVehicle", b =>
                {
                    b.Navigation("AssignQueues");
                });

            modelBuilder.Entity("Persistence.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Persistence.Seat", b =>
                {
                    b.Navigation("SeatVehicles");
                });

            modelBuilder.Entity("Persistence.StateAccount", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Persistence.StateHeadquarter", b =>
                {
                    b.Navigation("Headquarters");
                });

            modelBuilder.Entity("Persistence.StateTrip", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Persistence.TicketState", b =>
                {
                    b.Navigation("TravelTickets");
                });

            modelBuilder.Entity("Persistence.TravelRoute", b =>
                {
                    b.Navigation("DepartureTimes");

                    b.Navigation("RouteAssignments");

                    b.Navigation("TravelTickets");
                });

            modelBuilder.Entity("Persistence.Trip", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Persistence.TypeDocument", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Persistence.Vehicle", b =>
                {
                    b.Navigation("AssignQueues");

                    b.Navigation("DetailVehicles");

                    b.Navigation("DocumentVehicles");

                    b.Navigation("SeatVehicles");

                    b.Navigation("TravelTickets");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Persistence.VehicleState", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
